// Code generated by goctl. DO NOT EDIT.
package types

type AddRequest struct {
	Code string `json:"code"`
	Name string `json:"name"`
	Type uint64 `json:"type"`
}

type AddResponse struct {
}

type UpdateRequest struct {
	Id   uint64 `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
	Type uint64 `json:"type"`
}

type UpdateResponse struct {
}

type GetRequest struct {
	Id uint64 `json:"id"`
}

type GetResponse struct {
	Id   uint64 `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
	Type uint64 `json:"type"`
}

type DeleteRequest struct {
	Id uint64 `json:"id"`
}

type DeleteResponse struct {
}
