// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-zero-courseware/courseware/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/courseware/add",
				Handler: coursewareAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/courseware/update",
				Handler: coursewareUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/courseware/get",
				Handler: coursewareGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/courseware/delete",
				Handler: coursewareDeleteHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
